services:
  nats:
    image: nats:latest
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats/data:/data
      - ./nats/config/server.conf:/config/server.conf

  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    ports:
      - "31311:31311"  # Порт для доступа к NATS NUI
    volumes:
      - ./nui/db:/db
    depends_on:
      - nats

  bot:
    image: 'vangerm/cbs_news_bot:v0.2.4'
    container_name: cbs_news_bot
    restart: 'unless-stopped'
    env_file: './bot/.env'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # volumes:
    #   - ./bot/loger:/loger
    depends_on:
      - 'nats-nui'

  microservice_vk:
    image: 'vangerm/microservice:v0.1.2'
    container_name: microservice
    restart: 'unless-stopped'
    env_file: './microservice_vk/.env'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # volumes:
    #   - ./microservice_vk/loger:/loger
    depends_on:
      - 'bot'